### ISSUE TITLE
.NET6 WebAssembly Error

### ISSUE THREAD

**Issue by sinisteralex** [shimat/opencvsharp_blazor_sample#4]
Hello.
I have started using this library to do some experiments with OpenCV and WebAssembly.
The error underneath is a bit strange.

The code the error is pointing to is:

**`srcMat ??= Mat.FromImageData(imageBytes);`**

Error in browser:

blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 ---> OpenCvSharp.OpenCvSharpException: OpenCvSharpExtern
 ---> System.DllNotFoundException: OpenCvSharpExtern
   at OpenCvSharp.Internal.NativeMethods.TryPInvoke()
   --- End of inner exception stack trace ---
   at OpenCvSharp.Internal.NativeMethods.TryPInvoke()
   at OpenCvSharp.Internal.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.Cv2.ImDecode(ReadOnlySpan`1 span, ImreadModes flags)
   at OpenCvSharp.Cv2.ImDecode(Byte[] buf, ImreadModes flags)
   at OpenCvSharp.Mat.ImDecode(Byte[] imageBytes, ImreadModes mode)
   at OpenCvSharp.Mat.FromImageData(Byte[] imageBytes, ImreadModes mode)
   at MudBlazorBlazor.Pages.OpenCV.OnAfterRenderAsync(Boolean firstRender) in D:\Repos\repos .NET\MudBlazorBlazor\MudBlazorBlazor\Pages\OpenCV.razor:line 53
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by shimat** [comment]
Sorry for the long silence here.

This was caused by a mismatch between the native library's file name (`libOpenCvSharpExtern.a`) and the P/Invoke module name declared on the managed side (`OpenCvSharpExtern`, no `lib` prefix) - the wasm toolchain derives the P/Invoke module name from the file name verbatim, so this left the P/Invoke table empty (tracked upstream as opencvsharp#2039). This repo works around it by re-referencing a locally renamed copy of the `.a` file before the native build. The project has also since moved to .NET 10 / OpenCvSharp5. I just verified the app loads and runs OpenCvSharp calls fine on the current live demo, so closing this out - please reopen if you still hit a DllNotFoundException on a recent build.
